# Generated by Django 4.0 on 2023-05-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_alter_theme_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='category',
        ),
        migrations.AddField(
            model_name='theme',
            name='category',
            field=models.ManyToManyField(to='models_app.Category', verbose_name='Категория'),
        ),
    ]
