# Generated by Django 4.0 on 2023-07-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_remove_theme_category_theme_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Deutsch', 'Deutsch'), ('Español', 'Español'), ('Português', 'Português'), ('Français', 'Français'), ('Italiano', 'Italiano'), ('Polski', 'Polski'), ('Русский', 'Русский')], default='English', max_length=15, verbose_name='Язык'),
        ),
    ]
